### PR TITLE
Must not assume that external functions are pure

### PR DESCRIPTION
**Pull request by tbeu**
It is nowhere said in the MLS that external functions have to be pure and thus can be assigned to a (constant) parameter. Assume that the external function is impure (e.g., a random number generator) then the assignment to a parameter would be invalid.

Since the goal of these models is to test the external "C" support according to MLS 12.9 the parameter keyword should be removed here.

@HansOlsson @sjoelund @perost FYI

### CODE REVIEW

**Comment by HansOlsson** [comment]
I cannot see this as being correct.

In Modelica 3.3r1 if the function is not pure we are neither allowed to do:
parameter Real x=impureFunction();
nor:
Real x=impureFunction();
---
With the prefix keyword impure it is stated that a Modelica function is impure and it is only allowed to call such a function from within:
* another function marked with the prefixes impure or pure
* a when-equation, or
* a when-statement.
---
In Modelica 3.2 you were also allowed to call impure functions during initialization, which might generously be interpreted as allowing 'parameter Real x=impureFunction();' since parameter values are evaluated during initialization.
--
One could consider extending the rules in 3.3r1 to allow initial equations, except that it will not work well if we get algebraic loops.

**Comment by tbeu** [comment]
Thanks for clarification on the generous tool interpretation.

Since the ModelicaCompliance.Functions.External models are designed to test for MLS 12.9 I still would prefer to remove the `parameter` keyword here and add one new test model for this generous interpretation in MLS 3.2 that external functions are assumed to be pure if evaluated during initialization.

**Comment by HansOlsson** [comment]
I looked more, and the functions are pure - and thus it should be legal both with and without the parameter (and there is no possibility to mark a function as impure in MLS 3.2; they are in general assumed to be pure - except in some cases - which isn't very clear). 

Thus I would propose to have both the parameter-one and the non-parameter-one in at least one of the examples (for these pure functions).

**Comment by tbeu** [comment]
>  they are in general assumed to be pure

This is Modelica Compliance against the MLS 3.2. We cannot test Modelica compliance against assumptions if is missing there.

> except in some cases

Which would be interesting.

> Thus I would propose to have both the parameter-one and the non-parameter-one in at least one of the examples.

Agreed (as I also proposed above). Maybe the test models should be duplicated for the pure case (as is) and the impure case (as proposed by this PR).

**Comment by perost** [comment]
This compliance library is actually meant to test compliance to Modelica 3.2rev2, according to the original contract, and the MA hasn't said otherwise. And as Hans says it seems that all external functions are considered pure in 3.2rev2, except for when they aren't. So I would say that these tests are ok, but more tests could be added that specifically tests pure/impure external functions.

**Comment by tbeu** [comment]
@perost This again means we test against assumptions that are not written in MLS 3.2r2. If there will be a MLS 3.2r3 which says that external functions are (almost always) pure then the test models are fine. But currently there is no such claim in the MLS.

**Comment by perost** [comment]
@tbeu 3.2r2 says that all Modelica functions are pure, the only exception being impure external functions and functions which call impure functions. It also says that it's up to the external function's implementor to maintain this property. My interpretation is therefore that all external functions should be assumed to be pure, and it's up to the user of the external function to use impure functions properly. This is just an assumption as you say, but without assumptions there wouldn't be many test models in this library.

**Comment by tbeu** [comment]
Sorry, my interpretation is that all external functions should assumed to be impure. You never know what happens externally (unless stated by the pure keyword which we do not have in MLS 3.2r2).

**Comment by HansOlsson** [comment]
I don't see anything supporting all external functions being impure in MSL 3.2r2, since impure external functions is stated as being an exceptional case and the comment "The above implies that if all external functions that are used are pure then all Modelica functions are pure." would be meaningless if we assumed that external functions were impure (without any way of changing that assumption).

One could argue that the purity of external functions is unknown in 3.2r2 (similarly as functions in e.g. C). But the translator is allowed to make assumptions assuming the functions are pure (according to section 3.3) - except if the functions are only used in when-statements and initialization.
(This assumes that there is a minor typo in 3.2r2 - "only" is implied, but missing from the description of where impure functions can be used.)

The argument is that if we have 'Real a=externalFunction();' we can deduce that externalFunction is not pure (according to  section 12.3) and thus it must give the same value all the time, and thus we can use the normal mathematical optimizations in section 3.3. People familiar with how optimizing C-compiler overuse the standard will recognize that this means that if we have:
   Real a=externalFunction();
   Real b;
equation
  when sample(...) then
      b=externalFunction();
  end when;
We can optimize the when-clause-equation to 'b=a'; since externalFunction must be pure since called outside of a when-clause.

The problem with 3.2r2 is that if an impure function is used inappropriately the result might be wrong, but we don't know if the problem is that the function shouldn't be impure or that it the function shouldn't be used at that place. The changes in 3.3r1 mean that we can decide what the error is (and automatically detect one of them).

Additionally in 3.3r1 an external function is as default pure; you have to use "impure" if you want to make it clear that it is impure. I assume that was intended to be as compatible as possible with 3.2r2 - i.e. same default behavior.

**Comment by tbeu** [comment]
@HansOlsson OK, need to live with it. Thanks for contribution.

@perost I'll leave this issue open for you to add a new test model where an external function (e.g., an impure RNG) is not assigned to a parameter.

**Comment by tbeu** [comment]
In [tbeu/ExternData](https://github.com/tbeu/ExternData) parameters are initialized by external functions like this
```mo
parameter Real p(fixed=false);
initial equation
  p = externalFunction(constantArgument);
```
In my opinion this solution is standard-conform Modelica and not based on assumptions if the external function is pure or impure. I propose to also add one test case for such a scenario. @perost Can/will you do it?
Of course it is more convenient for the user to edit/see the parameter initialization in the dialog instead of an initial equation.

**Comment by perost** [comment]
>@perost Can/will you do it?
If you wish to have tests added anytime soon, you'd be better off doing it yourself.

**Comment by HansOlsson** [comment]
I don't see how this solves the problem. A solver could still use a non-linear solver that evaluates 
externalFunction(constantArgument) multiple times (even if in an initial equation).

What I think we should add is just a test using an impure function as follows (which will fail if the impure function is optimized assuming it is pure):
```Modelica
  function impureFunction
     output Real y;
     external "C";
     annotation(Include="double impureFunction() {static double x=0;x+=1;return x;}");
  end impureFunction;
  Real x,y;
equation
  when sample(1e-3,1e-3) then
     x=impureFunction();
     y=x-pre(x);
  end when;
  assert(time<1e-3 or abs(y-1)<1e-3,"Difference should be 1 when sampling starts");
```

**Comment by HansOlsson** [comment]
As far as I can see the conclusion was to not add the original PR.

**Pull request closed without merging**
